export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
export const SEARCH_PRODUCTS_COMPLETE = 'SEARCH_PRODUCTS_COMPLETE';
export const SEARCH_PRODUCTS_RESET = 'SEARCH_PRODUCTS_RESET';

export const SEARCH_PRODUCTS_BY_ID_START = 'SEARCH_PRODUCTS_BY_ID_START';
export const SEARCH_PRODUCTS_BY_ID_ERROR = 'SEARCH_PRODUCTS_BY_ID_ERROR';
export const SEARCH_PRODUCTS_BY_ID_COMPLETE = 'SEARCH_PRODUCTS_BY_ID_COMPLETE';
export const SEARCH_PRODUCTS_BY_ID_RESET = 'SEARCH_PRODUCTS_BY_ID_RESET';
export const SEARCH_USER_BY_ID_RESET_ERROR = 'SEARCH_USER_BY_ID_RESET_ERROR';


export const SEARCH_USER_BY_ID_START = 'SEARCH_USER_BY_ID_START';
export const SEARCH_USER_BY_ID_ERROR = 'SEARCH_USER_BY_ID_ERROR';
export const SEARCH_USER_BY_ID_COMPLETE = 'SEARCH_USER_BY_ID_COMPLETE';
export const SEARCH_USER_BY_ID_RESET = 'SEARCH_USER_BY_ID_RESET';

export const SEARCH_USER_ORDERS_START = 'SEARCH_USER_ORDERS_START';
export const SEARCH_USER_ORDERS_ERROR = 'SEARCH_USER_ORDERS_ERROR';
export const SEARCH_USER_ORDERS_COMPLETE = 'SEARCH_USER_ORDERS_COMPLETE';
export const SEARCH_USER_ORDERS_RESET = 'SEARCH_USER_ORDERS_RESET';