export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
export const SEARCH_PRODUCTS_COMPLETE = 'SEARCH_PRODUCTS_COMPLETE';
export const SEARCH_PRODUCTS_RESET = 'SEARCH_PRODUCTS_RESET';

export const SEARCH_PRODUCTS_BY_ID_START = 'SEARCH_PRODUCTS_BY_ID_START';
export const SEARCH_PRODUCTS_BY_ID_ERROR = 'SEARCH_PRODUCTS_BY_ID_ERROR';
export const SEARCH_PRODUCTS_BY_ID_COMPLETE = 'SEARCH_PRODUCTS_BY_ID_COMPLETE';
export const SEARCH_PRODUCTS_BY_ID_RESET = 'SEARCH_PRODUCTS_BY_ID_RESET';
export const SEARCH_USER_BY_ID_RESET_ERROR = 'SEARCH_USER_BY_ID_RESET_ERROR';


export const SEARCH_USER_BY_ID_START = 'SEARCH_USER_BY_ID_START';
export const SEARCH_USER_BY_ID_ERROR = 'SEARCH_USER_BY_ID_ERROR';
export const SEARCH_USER_BY_ID_COMPLETE = 'SEARCH_USER_BY_ID_COMPLETE';
export const SEARCH_USER_BY_ID_RESET = 'SEARCH_USER_BY_ID_RESET';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_COMPLETE = 'CREATE_USER_COMPLETE';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';

export const SEARCH_USER_ORDERS_START = 'SEARCH_USER_ORDERS_START';
export const SEARCH_USER_ORDERS_ERROR = 'SEARCH_USER_ORDERS_ERROR';
export const SEARCH_USER_ORDERS_COMPLETE = 'SEARCH_USER_ORDERS_COMPLETE';
export const SEARCH_USER_ORDERS_RESET = 'SEARCH_USER_ORDERS_RESET';

export const SEARCH_ORDER_BY_USER_START = 'SEARCH_ORDER_BY_USER_START';
export const SEARCH_ORDER_BY_USER_ERROR = 'SEARCH_ORDER_BY_USER_ERROR';
export const SEARCH_ORDER_BY_USER_COMPLETE = 'SEARCH_ORDER_BY_USER_COMPLETE';
export const SEARCH_ORDER_BY_USER_RESET = 'SEARCH_ORDER_BY_USER_RESET';

export const UPDATE_USER_INFO_START = 'UPDATE_USER_INFO_START';
export const UPDATE_USER_INFO_ERROR = 'SEARCH_ORDER_BY_USER_ERROR';
export const UPDATE_USER_INFO_COMPLETE = 'UPDATE_USER_INFO_COMPLETE';
export const UPDATE_USER_INFO_RESET = 'UPDATE_USER_INFO_RESET';

export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_COMPLETE = 'CREATE_PRODUCT_COMPLETE';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';

export const CREATE_ORDER_DETAIL_START = 'CREATE_ORDER_DETAIL_START';
export const CREATE_ORDER_DETAIL_ERROR = 'CREATE_ORDER_DETAIL_ERROR';
export const CREATE_ORDER_DETAIL_COMPLETE = 'CREATE_ORDER_DETAIL_COMPLETE';
export const CREATE_ORDER_DETAIL_RESET = 'CREATE_ORDER_DETAIL_RESET';